### ISSUE TITLE
A Question about Restraining the Analyzer Depth 

### ISSUE THREAD

**Issue by CleanHit** [heremaps/oss-review-toolkit#2293]
Is it possible to restrain the depth of the `analyser` (and `scanner` if needed) to the first level of seen package? For example with some additional `--max-depth` command line option, instead of going recursively into the sub dependencies of each package and again into their sub dependencies and so on......

**Comment by CleanHit** [comment]
I understand that the replies in this post #2295 give an indirect answer to my question. However in some cases it is reasonable to limit the result to the first level of detected package dependencies. For example in case of creating a static contribution HTML for an application with the OSS Licenses that don't require the deeper knowledge of their recursive dependencies. 

If it is not possible to define an `--max-depth` option for the `Analyzer`, then I hope that the `analyzer-result.yml` file structure e.g.:

1. lib-dependency 1

    1. sub-dependency 1.1
        1. sub-dependency 1.1.1
        1. sub-dependency 1.1.2
    1. sub-dependency 1.2

2. lib-dependency 2

    1. sub-dependency 2.1
    1. sub-dependency 2.2
        1. sub-dependency 2.2.1
        1. sub-dependency 2.2.2

allows to minimize the information only to the lib-dependencies and create a smaller `analyzer-result.yml` file, that can be used by the `Scanner`, `Evaluator` and `Reporter`.

**Comment by sschuberth** [comment]
> I understand that the replies in this post #2295 give an indirect answer to my question.

Correct, the Analyzer is always supposed to get the full picture.

So the correct way to implement the feature you're looking for would to introduce some new type of [Exclude](https://github.com/heremaps/oss-review-toolkit/blob/05fa56bd1989b549161bfee7763c3552dc28ea05/model/src/main/kotlin/config/Excludes.kt#L31) that allows to exclude packages based on certain properties, like their depth in the dependency tree.

However, personally I have mixed feelings about implementing a feature like this, because from a legal point of view it does not matter how deep a dependency occurs in your tree. You have to comply to its license obligations independently of the depth.

**Comment by CleanHit** [comment]
I've went over my `analyzer-result.yml` file and the produced **cycloneDX** `bom.xml` again. And I've noticed that the packages where listed only once (per version) in the `bom.xml` file even if they appeared many times recursively (as a sub-dependency) in the `analyzer-result.yml` file. Therefore, the produced `bom.xml` file is sufficient to create those **static contribution HTMLs**.

**Comment by sschuberth** [comment]
> And I've noticed that the packages where listed only once (per version) in the `bom.xml` file even if they appeared many times recursively (as a sub-dependency) in the `analyzer-result.yml` file.

Correct, the CycloneDX BOM format does not support expressing any hierarchy, and the packages are just a flat de-duplicated list of all transitive dependencies, very similar to the [packages section](https://github.com/heremaps/oss-review-toolkit/blob/beb527b4e5156f0117b11688a6728fa1cde0496b/scanner/src/funTest/assets/analyzer-result.yml#L56) in an Analyzer result file.
