### ISSUE TITLE
Am I right in thinking that analyser is trusting package-manager metadata?

### ISSUE THREAD

**Issue by devcurmudgeon** [heremaps/oss-review-toolkit#625]
In general I've been advocating building everything from source, so that we can be sure that we are working with known components (and extra points for verifying bit-for-bit reproducibility).

If we trust the package managers there are at least a couple of risks:
- the metadata is wrong (someone forgot to bump version information, or similar)
- the content is wrong (maybe it's been compromised, or we've been pointed at a fake url)

**Comment by sschuberth** [comment]
Thanks for following up on our brief discussion at [FOSS Backstage](https://foss-backstage.de/session/oss-review-toolkit-automating-open-source-compliance-within-cicd)!

I absolutely agree trusting the package manager's meta-data bears risks. Simple cases related to "someone forgot to bump version" are caught by the scanner which tries to match versions to VCS revisions in order to download the correct source code (the analyzer does not catch this as it's supposed to simply capture reality, like doing a "stocktaking").

However, of course some evil person could make the meta-data of some binary package point to a potentially completely unrelated source code repository. That repository could contain the revision as listed in the meta-data, and have a tag matching the version listed in the meta-data, but the contained source code is not actually what was used to build the binary. This is not something we guard against currently.

For some languages implementing such a check would probably be fairly doable: Like all languages / package managers where the "binary" is in fact just a ZIPped version of the source code (NPM, PIP, Bundler etc.). For such cases one could extract the packaged source code and compare it to the VCS repository contents. You probably need to apply some fuzziness to account for expanded templates and code generated at packaging time etc. But then again this fuzziness could also miss exactly those "evil" modifications you'd like to detect.

For other languages, like Java, where the binary contains compiled code, I currently don't see how to reliably verify that the source code pointed to actually is the source code the binary was created from. Of course you could re-compile the source code and try to compare the binaries, but that will hardly get you exact matches as things like the compiler version and flags influence the build. Also the other way around, to decompile the binaries an comparing to the source code, is not feasible.

All in all an interesting topic to discuss, and we're certainly open to suggestions regarding the implementation, even if the primary use-case for this toolkit is not security but compliance checks.

**Comment by sschuberth** [comment]
Ensuring that source code pointed to by meta-data actually matches the binary is current out of scope, so I'm closing this for now.
