### ISSUE TITLE
Display copyright information in scan results: Gradle/Java

### ISSUE THREAD

**Issue by annania** [heremaps/oss-review-toolkit#906]
Copyright information should be displayed in results file for all project/language types. Would like the java/gradle combination prioritized over others. Scancode has copyright information

**Comment by sschuberth** [comment]
Scan results, like e.g. [this test file](https://github.com/heremaps/oss-review-toolkit/blob/e1630396a45de2690981fcffc0bf4b2eb75c8bdc/model/src/test/assets/expected-scan-results.yml#L18), actually *do* have license / copyrights pairs. That's independent of the language as scanners like ScanCode simply treat everything as plain text. Is it that what you are looking for?

**Comment by annania** [comment]
Is this results from the scanner? My scanner results do not have any copyright information. Maybe I am running with an older version. Is there a specific branch that is more up-to-date? or is this a new feature (within the past month or so)?

**Comment by sschuberth** [comment]
Yes, these are results from the scanner, but currently this is only supported for ScanCode as the scanner. `master` is what's most up to date and what we're using ourselves internally. The feature is [available since Jul 11, 2018](https://github.com/heremaps/oss-review-toolkit/pull/594).

**Comment by annania** [comment]
Copyright information is necessary for Disclosure/Manifest documents. I re-ran a scan of a java/gradle project. In scan-result.yml there is no copyright information. I see that scancode ran with the --copyright flag enabled:

 scanner:
          name: "scancode"
          version: "2.9.2"
          configuration: "--copyright --license --info --strip-root --timeout 300\
            \ --json-pp"
        summary:

But, there is no copyright attribute or information in scan-result.yml.

**Comment by annania** [comment]
I did a pull on master, and am running at:

commit 2bff75c58d6cbef4a4b9d73269d087193e45d177 (HEAD -> master)
Author: Sebastian Schuberth <sebastian.schuberth@here.com>
Date:   Tue Sep 25 12:46:27 2018 +0200

    Downloader: Fix logging the detected VCS type
    
    This is a fixup for ccd8256.

**Comment by sschuberth** [comment]
Would you be able to share the project you're scanning, or reproduce the issue with a publicly available project?

**Comment by annania** [comment]
I cannot share the project, I will try to reproduce with an OS project.

**Comment by annania** [comment]
Coming back to this, I see that I am getting: Caused by: DownloadException: No VCS URL provided for 'Gradle:::'. Please make sure the release POM file includes the SCM connection, see: https://docs.gradle.org/current/userguide/publishing_maven.html#example_customizing_the_pom_file

What is needed from the VCS? Can it look locally for the files instead? Is this what it is doing?

**Comment by sschuberth** [comment]
> What is needed from the VCS?

The source code of the dependency. In order to scan the source code with a license scanner, the source code needs to be available. And in order to find the source code, the dependency package's meta-data needs to point at it. In case of Maven artifacts used by Gradle projects this is usually done via the published POM's SCM tag, see https://maven.apache.org/pom.html#SCM.

Alternatively, ORT will fall back to scanning the source code as published by a source artifact, if any.

> Can it look locally for the files instead?

That's a relevant question as in your case the error seems to refer to a local Gradle project (`'Gradle:::'`) and not to a Maven dependency of that Gradle project. The source code of the project to scan itself (not its dependencies) should already be checked out locally, so the source code should be known.

> The code base is on Github enterprise, will this conflict with the scanning strategy?

No. On which service the source code is hosted does not matter as long as it is Git (or any of the over supported VCSes) and you have proper access permissions.

I'd highly recommend to run through the [Gettings Started guide](https://github.com/heremaps/oss-review-toolkit/blob/master/docs/GettingStarted.md) based on an example project first, to get a better understanding of how ORT's bits & pieces work together.

**Comment by sschuberth** [comment]
Closing this for now due to a lack of feedback. Feel free to reopen this if you still see the issue.
